name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.6'

    - name: Install dependencies
      run: |
        pip install -r docs/requirements.txt
        pip install --upgrade sphinx

    - name: Install pandoc
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.14/pandoc-2.14-linux-amd64.tar.gz
        tar xvzf pandoc-2.14-linux-amd64.tar.gz
        sudo cp pandoc-2.14/bin/pandoc /usr/local/bin/

    - name: Build documentation
      run: |
        make -C docs/ html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
